config/routes.rb
Food::Application.routes.draw do
  resources :fs

end

app/models/f.rb
class F < ActiveRecord::Base
  attr_accessible :desc, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fs_controller.rb
class FsController < ApplicationController
  # GET /fs
  # GET /fs.json
  def index
    @fs = F.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fs }
    end
  end

  # GET /fs/1
  # GET /fs/1.json
  def show
    @f = F.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @f }
    end
  end

  # GET /fs/new
  # GET /fs/new.json
  def new
    @f = F.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @f }
    end
  end

  # GET /fs/1/edit
  def edit
    @f = F.find(params[:id])
  end

  # POST /fs
  # POST /fs.json
  def create
    @f = F.new(params[:f])

    respond_to do |format|
      if @f.save
        format.html { redirect_to @f, notice: 'F was successfully created.' }
        format.json { render json: @f, status: :created, location: @f }
      else
        format.html { render action: "new" }
        format.json { render json: @f.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fs/1
  # PUT /fs/1.json
  def update
    @f = F.find(params[:id])

    respond_to do |format|
      if @f.update_attributes(params[:f])
        format.html { redirect_to @f, notice: 'F was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @f.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fs/1
  # DELETE /fs/1.json
  def destroy
    @f = F.find(params[:id])
    @f.destroy

    respond_to do |format|
      format.html { redirect_to fs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fs_helper.rb
module FsHelper
end

app/views/fs/_form.html.erb
<%= form_for(@f) do |f| %>
  <% if @f.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@f.errors.count, "error") %> prohibited this f from being saved:</h2>

      <ul>
      <% @f.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fs/edit.html.erb
<h1>Editing f</h1>

<%= render 'form' %>

<%= link_to 'Show', @f %> |
<%= link_to 'Back', fs_path %>

app/views/fs/index.html.erb
<h1>Listing fs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fs.each do |f| %>
  <tr>
    <td><%= f.name %></td>
    <td><%= f.desc %></td>
    <td><%= link_to 'Show', f %></td>
    <td><%= link_to 'Edit', edit_f_path(f) %></td>
    <td><%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New F', new_f_path %>

app/views/fs/new.html.erb
<h1>New f</h1>

<%= render 'form' %>

<%= link_to 'Back', fs_path %>

app/views/fs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @f.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @f.desc %>
</p>


<%= link_to 'Edit', edit_f_path(@f) %> |
<%= link_to 'Back', fs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>